services:
  mongo_db:
    container_name: mongo_db
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    container_name: express_api_container
    build: .
    ports:
      - 5001:8008
    environment:
      PORT: 8008
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: gameplatform
      NAME: GameDeveloper
      JWT_SECRET: abcdefghijklmnopqrstuvwxyz1234567890
    volumes:
      - /var/www/html/games:/app/games

volumes:
  mongo_db: {}
